/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 space.gltf 
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useMemo, useRef } from 'react'
import { useBounds, useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/space.gltf')
  const ref = useRef()
  useFrame((state, delta) => {
    // ref.current.rotation.x += delta * 0.3
    // ref.current.rotation.y += delta * 0.1
    // ref.current.position.z += -1
  })

  // const bbox = useMemo(() => {
  //   if (ref.current) {
  //     const box = new THREE.Box3().setFromObject(ref.current)
  //     return box
  //   }
  // }, [ref.current])

  // const center = bbox ? bbox.getCenter(new THREE.Vector3()) : [0, 0, 0]

  return (
    <group {...props} dispose={null}>
      <points
        color={'red'}
        ref={ref}
        position={[-1120, 1250, 0]}
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        // rotation={[-Math.PI / 2, 0, 0]}
        scale={10}
      />
    </group>
  )
}

useGLTF.preload('/space.gltf')

// OLD:
// (
//     <group {...props} dispose={null}>
//       <points
//         color={'red'}
//         ref={ref}
//         position={[-400, -200, -350]}
//         geometry={nodes.Object_2.geometry}
//         material={materials['Scene_-_Root']}
//         // rotation={[-Math.PI / 2, 0, 0]}
//         scale={3}
//       />
//     </group>
//   )
