/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 tiefighter.gltf 
Author: StarWars-Universe (https://sketchfab.com/SWU)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/tie-fighter-c306f5183f364176912d782b19474781
Title: TIE Fighter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const ref = useRef()
  useFrame((state, delta) => {
    // const t = state.clock.getElapsedTime()

    // ref.current.position.z -= 0.05

    //
    const t = state.clock.getElapsedTime()
    const speed = 1
    const angle = Math.PI / 4
    const dx = Math.cos(angle) * speed
    const dz = Math.sin(angle) * speed

    ref.current.position.x -= dx
    ref.current.position.z -= dz
  })

  const { nodes, materials } = useGLTF('/tiefighter.gltf')
  return (
    <group {...props} ref={ref} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[103.342, -207.109, 30.918]}>
            <group
              position={[-56.768, -28.895, -0.598]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={4.974}
            >
              <mesh
                geometry={nodes.Material1_1.geometry}
                material={materials['1_-_Standard.1']}
              />
              <mesh
                geometry={nodes.Material1_2.geometry}
                material={materials['1_-_Standard.1']}
              />
              <mesh
                geometry={nodes.Material1_3.geometry}
                material={materials['1_-_Standard.1']}
              />
              <mesh
                geometry={nodes.Material1_4.geometry}
                material={materials['1_-_Standard.1']}
              />
              <mesh
                geometry={nodes.Material1_5.geometry}
                material={materials['1_-_Standard.1']}
              />
            </group>
            <group
              position={[7.487, -9.873, -0.871]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.964}
            >
              <mesh
                geometry={nodes.Material1_7.geometry}
                material={materials['1_-_Standard.1']}
              />
              <mesh
                geometry={nodes.Material2.geometry}
                material={materials['2_-_Standard']}
              />
            </group>
            <group
              position={[-166.61, 3.749, -0.628]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
              scale={[1.135, 1.135, 0.218]}
            >
              <mesh
                geometry={nodes.Material1_10.geometry}
                material={materials['1_-_Standard']}
              />
              <mesh
                geometry={nodes.Material2_1.geometry}
                material={materials['7_-_Standard']}
              />
            </group>
            <group
              position={[152.459, 3.749, -0.628]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
              scale={[1.135, 1.135, 0.218]}
            >
              <mesh
                geometry={nodes.Material1_11.geometry}
                material={materials['1_-_Standard']}
              />
              <mesh
                geometry={nodes.Material2_2.geometry}
                material={materials['7_-_Standard']}
              />
            </group>
            <mesh
              geometry={nodes.Material1.geometry}
              material={materials['1_-_Standard']}
              position={[-145.057, 7.051, 20.708]}
              rotation={[0, 0.227, 0]}
            />
            <mesh
              geometry={nodes.Material1_6.geometry}
              material={materials['7_-_Standard.1']}
              position={[1.004, 48.237, 44.084]}
              scale={[0.44, 0.505, 0.44]}
            />
            <mesh
              geometry={nodes.Material1_8.geometry}
              material={materials['3_-_Standard']}
              position={[-15.106, 9.364, 31.589]}
              rotation={[0, 0, -1.966]}
              scale={3.003}
            />
            <mesh
              geometry={nodes.Material1_9.geometry}
              material={materials['2_-_Standard']}
              position={[1.082, 2.743, 55.943]}
              rotation={[-Math.PI, 0, 0]}
              scale={[4.094, 4.094, 1.507]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tiefighter.gltf')
