/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 xwing.gltf 
Author: GaryPhelps (https://sketchfab.com/GaryPhelps)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xwing-d34629ae9cf3432188545f36ac1d9cb8
Title: Xwing
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/xwing.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.blinn2SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.blinn5SG}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.blinn8SG}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.blinn8SG}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.blinn9SG}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.lambert4SG}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.lambert6SG}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.lambert7SG}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/xwing.gltf')
